### ISSUE TITLE
No such file or directory exception isn't catched and handled

### ISSUE THREAD

**Issue by Nicoretti** [esrlabs/bakeConv#2]
If bake config is called with the -f option and an invalid path is provided (e.g. to a file which does not exists), the thrown exception isn't catched and handled.

```
NiCoretti@Nc-ESRLabs: ~/VM_Projects/playground/project_template/main
◖Thu 21 | 13:48◗ ►  bakeConv --debug -f conversion_config/config/converter.config -p application
Reading config...
No such file or directory @ rb_sysopen - /Users/NiCoretti/VM_Projects/playground/project_template/main/conversion_config/config/converter.config
/Users/NiCoretti/.rvm/gems/ruby-2.1.2/gems/bakeConv-1.5.2/lib/ConfigParser.rb:67:in `rescue in readConfig': undefined method `back_trace' for #<Errno::ENOENT:0x007fc7340e5120> (NoMethodError)
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/gems/bakeConv-1.5.2/lib/ConfigParser.rb:16:in `readConfig'
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/gems/bakeConv-1.5.2/lib/bakeConverter.rb:113:in `main'
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/gems/bakeConv-1.5.2/lib/bakeConverter.rb:159:in `<top (required)>'
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/gems/bakeConv-1.5.2/bin/bakeConv:7:in `require_relative'
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/gems/bakeConv-1.5.2/bin/bakeConv:7:in `<top (required)>'
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/bin/bakeConv:23:in `load'
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/bin/bakeConv:23:in `<main>'
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /Users/NiCoretti/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fraukeBL** [comment]
fixed in version 1.5.3
